name: "Build App for Development"

on:
  workflow_dispatch:

jobs:
  build-app:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust Nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: install frontend dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Set environment variables
        run: |
          echo "NOVA_CHANNEL=rift" >> $GITHUB_ENV
          echo "NOVA_GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "NOVA_BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV

      - name: build
        shell: bash
        env:
          NOVA_CHANNEL: ${{ env.NOVA_CHANNEL }}
          NOVA_GIT_HASH: ${{ env.NOVA_GIT_HASH }}
          NOVA_BUILD_TIME: ${{ env.NOVA_BUILD_TIME }}
        run: |
          export TAURI_SIGNING_PRIVATE_KEY=${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          export TAURI_SIGNING_PRIVATE_KEY_PASSWORD=${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          pnpm tauri build

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: Windows Embedded App
          path: src-tauri/target/release/novacl.exe
          retention-days: 14

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: Windows Bundled Installer
          path: src-tauri/target/release/bundle/
          retention-days: 14
